tap "bfontaine/utils"
tap "homebrew/cask"

cask "1password"
cask "alfred"
cask "docker"
cask "fantastical"
cask "mactex-no-gui"
cask "meetingbar"
cask "refined-github-safari"
cask "signal"
cask "slack"

brew "bfontaine/utils/zprint"
brew "circleci"
