tap "homebrew/cask"

cask "1password"
cask "alfred"
cask "docker"
cask "fantastical"
cask "meetingbar"
cask "minecraft"
cask "refined-github-safari"
cask "signal"
cask "slack"
cask "spotify"
cask "zoom"
