#+TITLE: International Support
#+AUTHOR: Stig Brautaset
#+OPTIONS: f:t h:4
#+PROPERTY: header-args:emacs-lisp :tangle yes
#+PROPERTY: header-args:sh         :tangle yes
#+PROPERTY: header-args            :results silent
#+STARTUP: content
* Introduction

  I'm Norwegian, but use a GB keyboard. I also use Dvorak keyboard
  layout. I also have Polish colleagues whose names I don't want to
  mangle completely. Keep this in mind if you find the below
  confusing.

* Always use UTF-8 encoding

  Let's always use UTF-8 encoding. Pretty, pretty please with sugar on top.

  #+BEGIN_SRC emacs-lisp
    (setq locale-coding-system 'utf-8)
    (set-terminal-coding-system 'utf-8)
    (set-keyboard-coding-system 'utf-8)
    (set-selection-coding-system 'utf-8)
    (prefer-coding-system 'utf-8)
  #+END_SRC

* Conveniently type Norwegian characters

  Let's define keybindings for the three additional Norwegian
  characters characters that I don't have natively on my British
  keyboard.

  #+BEGIN_SRC emacs-lisp
    (global-set-key (kbd "s-'") (kbd "æ"))
    (global-set-key (kbd "s-\"") (kbd "Æ"))
    (global-set-key (kbd "s-O") (kbd "Ø"))
    (global-set-key (kbd "s-o") (kbd "ø"))
    (global-set-key (kbd "s-A") (kbd "Å"))
    (global-set-key (kbd "s-a") (kbd "å"))
    #+END_SRC

* Use Aspell with UK English Dictionary

  Configure Emacs to use the Queen's English for spell checking. Also,
  use /aspell/ rather than /ispell/.

  #+BEGIN_SRC emacs-lisp
    (setq ispell-program-name "aspell"
          ispell-dictionary "british")
  #+END_SRC

  Install aspell with the appropriate dictionary using brew.

  #+BEGIN_SRC sh
    brew install aspell
  #+END_SRC

* (Some) Polish Characters Support

  I have Polish colleagues whose names I don't want to mangle.

  #+BEGIN_SRC emacs-lisp
    (global-set-key (kbd "C-x 8 ' l") (kbd "ł"))
  #+END_SRC
