#+title: Notmuch

I currently use [[https://notmuchmail.org][Notmuch]] for reading and sending Email, as it has a
nice Emacs client.

* Configuring Notmuch

I no longer have two separate machines, but I rarely send work mail so
configure my private address to be the primary one.

#+begin_src conf :tangle ~/.notmuch-config :noweb yes :noweb yes
[database]
path=/Users/stig/.mail

[user]
name=Stig Brautaset
primary_email=stig@brautaset.org
other_email=stig@circleci.com

[new]
tags=new
ignore=.mbsyncstate;.mbsyncstate.journal;.mbsyncstate.lock;.mbsyncstate.new;.uidvalidity;.isyncuidmap.db;.DS_Store

[search]
exclude_tags=deleted;spam

[maildir]
synchronize_flags=true
#+end_src

* Script to run immediately before checking for new mail

Move messages based on tags, to avoid other email clients seing just a giant INBOX.

#+BEGIN_SRC sh :tangle ~/.mail/.notmuch/hooks/pre-new :shebang #!/bin/zsh :tangle-mode (identity #o755) :mkdirp t
set -euo pipefail
IFS=$'\n\t'

# Strip UIDs from filenames when moving mails so that mbsync doesn't
# get confused.
mv_without_uid () {
    while IFS= read -r name; do
        new_name="$(basename $name | awk -F ',' '{print $1}')"
	[ -f "$name" ] && mv -nv "$name" "$1/new/$new_name" | sed 's,/Users/stig/.mail/,,g'
    done
}

# Delete drafts immediately
notmuch search --output=files --format=text0 -- tag:deleted and tag:draft | xargs -0 rm -fv

# Delete old deleted and spam messages
notmuch search --output=files --format=text0 -- tag:deleted date:..6w | xargs -0 rm -fv
notmuch search --output=files --format=text0 -- tag:spam date:..3w | xargs -0 rm -fv

# Move deleted messages
notmuch search --output=files -- path:'home/**' and tag:deleted and not folder:home/Trash | mv_without_uid ~/.mail/home/Trash
notmuch search --output=files -- path:'work/**' and tag:deleted and not folder:work/Trash | mv_without_uid ~/.mail/work/Trash

# Move spam messages
notmuch search --output=files -- path:'home/**' and tag:spam and not folder:home/Spam | mv_without_uid ~/.mail/home/Spam
notmuch search --output=files -- path:'work/**' and tag:spam and not folder:work/Spam | mv_without_uid ~/.mail/work/Spam

# Move incorrectly-tagged spam OUT of Spam folder
notmuch search --output=files -- not tag:spam and folder:home/Spam | mv_without_uid ~/.mail/home/INBOX
notmuch search --output=files -- not tag:spam and folder:work/Spam | mv_without_uid ~/.mail/work/INBOX

# Archive messages
notmuch search --output=files -- not tag:inbox and folder:home/INBOX | mv_without_uid ~/.mail/home/Archive
notmuch search --output=files -- not tag:inbox and folder:work/INBOX | mv_without_uid ~/.mail/work/Archive

# Tag messages
notmuch tag +home -- tag:new and path:'home/**'
notmuch tag +work -- tag:new and path:'work/**'

# Remove 'new' tag for old messages
notmuch tag -new -- tag:new

# Pull new messages from upstream;
# Let hourly job handle updating upstream with local changes
mbsync --all --quiet --pull --new
#+END_SRC

* Script to run immediately after checking for new mail

Assign tags, partly based on server filtering.

I now Bcc myself on sent mail, so tag mail as =sent= based on sender
address, and remove it from my inbox.

Server-side filtered =spam= and mailing lists gets based on its
mailbox. (Though I don't currently subscribe to any high-volume
mailing lists.)

I also tag messages to particular aliases at my domain.

I order a lot from Amazon, and things doesn't always arrive straight
away. I tag order confirmations from Amazon for batch-processing once
a week, to make sure I don't miss checking up on missed orders.

#+BEGIN_SRC sh :tangle ~/.mail/.notmuch/hooks/post-new :shebang #!/bin/zsh :tangle-mode (identity #o755) :mkdirp t
notmuch tag --batch <<EOF
+inbox +home -- tag:new folder:home/INBOX
+inbox +work -- tag:new folder:work/INBOX

+spam +home  -- tag:new folder:home/Spam
+spam +work  -- tag:new folder:work/Spam

+sent -inbox +home -- tag:new from:stig@brautaset.org
+sent -inbox +work -- tag:new from:stig@circleci.com

+to_confirm -inbox -- tag:new from:auto-confirm@amazon.co.uk
+to_confirm -inbox -- tag:new from:bonjour@mademoisellemacaron.co.uk

EOF
#+END_SRC
