#+title: Notmuch

I currently use [[https://notmuchmail.org][Notmuch]] for reading and sending Email, as it has a
nice Emacs client.

* Configuring Notmuch

For work/life balance I add my work tag to excluded mail, to avoid
seeing work mail on my personal machine.

#+begin_src conf :tangle ~/.notmuch-config :noweb yes
[database]
path=/Users/stig/.mail

[user]
name=Stig Brautaset
primary_email=stig@brautaset.org
other_email=stig@circleci.com

[new]
tags=new
ignore=.mbsyncstate;.mbsyncstate.journal;.mbsyncstate.lock;.mbsyncstate.new;.uidvalidity;.isyncuidmap.db;.DS_Store

[search]
exclude_tags=deleted

[maildir]
synchronize_flags=true
#+end_src

* Script to run immediately before checking for new mail

Move messages based on tags, to avoid other email clients seing just a giant INBOX.

#+BEGIN_SRC sh :tangle ~/.mail/.notmuch/hooks/pre-new :shebang #!/bin/zsh :tangle-mode (identity #o755) :mkdirp t
set -euo pipefail
IFS=$'\n\t'

# Strip UIDs from filenames when moving mails so that mbsync doesn't
# get confused.
mv_without_uid () {
    while IFS= read -r name; do
        new_name="$(basename $name | awk -F ',' '{print $1}')"
	[ -f "$name" ] && mv -nv "$name" "$1/new/$new_name"
    done
}

echo "Pruning deleted drafts.."
notmuch search --output=files --format=text0 -- tag:deleted and tag:draft | xargs -0 rm -fv

echo "Expunge old deleted mail.."
notmuch search --output=files --format=text0 -- tag:deleted and date:..4w | xargs -0 rm -fv

echo "Delete old spam.."
notmuch search --output=files --format=text0 -- tag:spam and date:..6w | xargs -0 rm -fv

echo "Move deleted mail to Trash.."
notmuch search --output=files -- tag:deleted and tag:gandi and not folder:"gandi/Trash" | mv_without_uid ~/.mail/gandi/Trash
notmuch search --output=files -- tag:deleted and tag:gmail and not folder:"gmail/[Gmail]/Trash" | mv_without_uid ~/.mail/gmail/\[Gmail\]/Trash

echo "Move spam messages out of inbox.."
notmuch search --output=files -- tag:spam and folder:"gandi/INBOX" | mv_without_uid ~/.mail/gandi/Junk
notmuch search --output=files -- tag:spam and folder:"gmail/Inbox" | mv_without_uid ~/.mail/gmail/\[Gmail\]/Spam

echo "Move incorrectly-tagged spam to INBOX.."
notmuch search --output=files -- not tag:spam and folder:"gandi/Junk" | mv_without_uid ~/.mail/gandi/INBOX
notmuch search --output=files -- not tag:spam and folder:"gmail/[Gmail]/Spam" | mv_without_uid ~/.mail/gmail/INBOX

echo "Archive messages.."
notmuch search --output=files -- not tag:inbox and folder:"gandi/INBOX" | mv_without_uid ~/.mail/gandi/Archive

echo "Remove 'new' tag for old messages.."
notmuch tag -new -- tag:new

echo "Synchronise local mailbox with upstream.."
mbsync inboxes
#+END_SRC

* Script to run immediately after checking for new mail

Assign tags based on server filtering.

I tag sent mail and remove it from my inbox. I decide whether
it's sent mail based on which mailbox it's in on the server.

Spam, archived, and deleted messages gets tagged as such, based on
their mailboxes on the server.

I don't normally want to see mailing list posts in my inbox, so remove
that tag. (And add specific tags based on their lists.)

Messages to particular aliases at my domain also gets tagged
appropriately.

Order confirmation messages from Amazon gets tagged so I can
batch-process them once a week.

Finally I tag some persistent spammers that are pretty good at getting
through my provider's spam filter, so they don't bother me.

#+BEGIN_SRC sh :tangle ~/.mail/.notmuch/hooks/post-new :shebang #!/bin/zsh :tangle-mode (identity #o755) :mkdirp t
notmuch tag --batch <<EOF
+inbox -- tag:new folder:gandi/INBOX
+inbox -- tag:new folder:gmail/Inbox

-unread +sent -- tag:new path:/Sent/

+spam         -- tag:new path:/Junk/
+archived     -- tag:new path:/Archive/
+deleted      -- tag:new path:/Trash/

+gandi        -- tag:new path:"gandi/**"
+circleci     -- tag:new path:"gmail/**"

+lists +org-mode  -- tag:new to:emacs-orgmode@gnu.org
+lists +clojure	  -- tag:new to:clojure@googlegroups.com

+inbox +lists +tuls -- tag:new to:tuls@debussy.pauken.co.uk

+fam   -- tag:new to:fam@brautaset.org
+solve -- tag:new to:solve@brautaset.org

+lobsters    -- tag:new from:nobody@lobste.rs
+github      -- tag:new from:notifications@github.com
+pagerduty   -- tag:new from:no-reply@pagerduty.com
+linkedin    -- tag:new from:messaging-digest-noreply@linkedin.com
+patreon     -- tag:new from:bingo@patreon.com
+guitarhacks -- tag:new from:support@guitarhacks.com

# Help me periodically confirm receipt of orders
+to_confirm -inbox -- tag:new from:auto-confirm@amazon.co.uk

# Persistent spammers
+spam -inbox -- tag:new from:alexandre@les-caves.fr
+spam -inbox -- tag:new from:alexandre@agence-gwa.com
+spam -inbox -- tag:new from:replies@oracle-mail.com

EOF
#+END_SRC
