#+title: Notmuch

I currently use [[https://notmuchmail.org][Notmuch]] for reading and sending Email, as it has a
nice Emacs client.

* Configuring Notmuch

For work/life balance I add my work tag to excluded mail, to avoid
seeing work mail on my personal machine.

#+name: primary-email
#+begin_src emacs-lisp
(if (string-match "margil" (system-name))
    "stig@brautaset.org"
  "stig@circleci.com")
#+end_src

#+name: other-email
#+begin_src emacs-lisp
(if (string-match "margil" (system-name))
    "stig@circleci.com"
  "stig@brautaset.org")
#+end_src


#+begin_src conf :tangle ~/.notmuch-config :noweb yes :noweb yes
[database]
path=/Users/stig/.mail

[user]
name=Stig Brautaset
primary_email=<<primary-email()>>
other_email=<<other-email()>>

[new]
tags=new
ignore=.mbsyncstate;.mbsyncstate.journal;.mbsyncstate.lock;.mbsyncstate.new;.uidvalidity;.isyncuidmap.db;.DS_Store

[search]
exclude_tags=deleted;spam

[maildir]
synchronize_flags=true
#+end_src

* Script to run immediately before checking for new mail

Move messages based on tags, to avoid other email clients seing just a giant INBOX.

#+BEGIN_SRC sh :tangle ~/.mail/.notmuch/hooks/pre-new :shebang #!/bin/zsh :tangle-mode (identity #o755) :mkdirp t
set -euo pipefail
IFS=$'\n\t'

# Strip UIDs from filenames when moving mails so that mbsync doesn't
# get confused.
mv_without_uid () {
    while IFS= read -r name; do
        new_name="$(basename $name | awk -F ',' '{print $1}')"
	[ -f "$name" ] && mv -nv "$name" "$1/new/$new_name" | sed 's,/Users/stig/.mail/,,g'
    done
}

# Delete old deleted and spam messages
notmuch search --output=files --format=text0 -- tag:deleted date:..6w | xargs -0 rm -fv
notmuch search --output=files --format=text0 -- tag:spam date:..6w | xargs -0 rm -fv

# Move deleted messages
notmuch search --output=files -- tag:deleted and not folder:Trash | mv_without_uid ~/.mail/Trash

# Move spam messages
notmuch search --output=files -- tag:spam and not folder:Spam | mv_without_uid ~/.mail/Spam

# Move incorrectly-tagged spam OUT of Spam folder
notmuch search --output=files -- not tag:spam and folder:Spam | mv_without_uid ~/.mail/INBOX

# Archive messages
notmuch search --output=files -- not tag:inbox and folder:INBOX | mv_without_uid ~/.mail/Archive

# Remove 'new' tag for old messages
notmuch tag -new -- tag:new

# Synchronise local mailbox with upstream
mbsync -aq
#+END_SRC

* Script to run immediately after checking for new mail

Assign tags, partly based on server filtering.

I now Bcc myself on sent mail, so tag mail as =sent= based on sender
address, and remove it from my inbox.

Server-side filtered =spam= and mailing lists gets based on its
mailbox. (Though I don't currently subscribe to any high-volume
mailing lists.)

I also tag messages to particular aliases at my domain.

I order a lot from Amazon, and things doesn't always arrive straight
away. I tag order confirmations from Amazon for batch-processing once
a week, to make sure I don't miss checking up on missed orders.

#+BEGIN_SRC sh :tangle ~/.mail/.notmuch/hooks/post-new :shebang #!/bin/zsh :tangle-mode (identity #o755) :mkdirp t
notmuch tag --batch <<EOF
+inbox -- tag:new folder:INBOX
+spam  -- tag:new folder:Spam

+sent -inbox -- tag:new from:stig@brautaset.org
+sent -inbox -- tag:new from:stig@circleci.com

+fam   -- tag:new to:fam@brautaset.org
+solve -- tag:new to:solve@brautaset.org

+to_confirm -inbox -- tag:new from:auto-confirm@amazon.co.uk
+to_confirm -inbox -- tag:new from:bonjour@mademoisellemacaron.co.uk

EOF
#+END_SRC
