#+title: Notmuch

I currently use [[https://notmuchmail.org][Notmuch]] for reading and sending Email, as it has a
nice Emacs client.

* Configuring Notmuch

For work/life balance I add my work tag to excluded mail, to avoid
seeing work mail on my personal machine.

#+name: primary-email
#+begin_src emacs-lisp
(if (string-match "margil" (system-name))
    "stig@brautaset.org"
  "stig@circleci.com")
#+end_src

#+name: other-email
#+begin_src emacs-lisp
(if (string-match "margil" (system-name))
    "stig@circleci.com"
  "stig@brautaset.org")
#+end_src


#+begin_src conf :tangle ~/.notmuch-config :noweb yes :noweb yes
[database]
path=/Users/stig/.mail

[user]
name=Stig Brautaset
primary_email=<<primary-email()>>
other_email=<<other-email()>>

[new]
tags=new
ignore=.mbsyncstate;.mbsyncstate.journal;.mbsyncstate.lock;.mbsyncstate.new;.uidvalidity;.isyncuidmap.db;.DS_Store

[search]
exclude_tags=deleted;spam

[maildir]
synchronize_flags=true
#+end_src

* Script to run immediately before checking for new mail

Move messages based on tags, to avoid other email clients seing just a giant INBOX.

#+BEGIN_SRC sh :tangle ~/.mail/.notmuch/hooks/pre-new :shebang #!/bin/zsh :tangle-mode (identity #o755) :mkdirp t
set -euo pipefail
IFS=$'\n\t'

# Strip UIDs from filenames when moving mails so that mbsync doesn't
# get confused.
mv_without_uid () {
    while IFS= read -r name; do
        new_name="$(basename $name | awk -F ',' '{print $1}')"
	[ -f "$name" ] && mv -nv "$name" "$1/new/$new_name"
    done
}

# Delete old spam and list messages
notmuch tag --batch <<EOF
+deleted -- tag:lists and not tag:archived and date:..6w
+deleted -- tag:spam and date:..6w
EOF

# Move deleted messages
notmuch search --output=files -- tag:deleted and not folder:Trash | mv_without_uid ~/.mail/Trash

# Move spam messages
notmuch search --output=files -- tag:spam and not tag:deleted and not folder:Spam | mv_without_uid ~/.mail/Spam

# Move incorrectly-tagged spam OUT of Spam folder
notmuch search --output=files -- not tag:spam and folder:Spam | mv_without_uid ~/.mail/INBOX

# Archive messages
notmuch search --output=files -- tag:archived not folder:Archive | mv_without_uid ~/.mail/Archive

# Remove 'new' tag for old messages
notmuch tag -new -- tag:new

# Synchronise local mailbox with upstream
mbsync -a
#+END_SRC

* Script to run immediately after checking for new mail

Assign tags based on server filtering.

I tag sent mail and remove it from my inbox. I decide whether
it's sent mail based on which mailbox it's in on the server.

Spam, archived, and deleted messages gets tagged as such, based on
their mailboxes on the server.

I don't normally want to see mailing list posts in my inbox, so remove
that tag. (And add specific tags based on their lists.)

Messages to particular aliases at my domain also gets tagged
appropriately.

Order confirmation messages from Amazon gets tagged so I can
batch-process them once a week.

Finally I tag some persistent spammers that are pretty good at getting
through my provider's spam filter, so they don't bother me.

#+BEGIN_SRC sh :tangle ~/.mail/.notmuch/hooks/post-new :shebang #!/bin/zsh :tangle-mode (identity #o755) :mkdirp t
notmuch tag --batch <<EOF
+inbox        -- tag:new folder:INBOX
-unread +sent -- tag:new folder:Sent
+spam         -- tag:new folder:Spam

+lists +org-mode    -- tag:new folder:org-mode
+inbox +lists +tuls -- tag:new folder:tuls

+fam   -- tag:new to:fam@brautaset.org
+solve -- tag:new to:solve@brautaset.org

+to_confirm -inbox -- tag:new from:auto-confirm@amazon.co.uk

EOF
#+END_SRC
