#+title: Notmuch

I currently use [[https://notmuchmail.org][Notmuch]] for reading and sending Email, as it has a
nice Emacs client.

* Configuring Notmuch

For work/life balance I add my work tag to excluded mail, to avoid
seeing work mail on my personal machine.

#+name: ignore-tag
#+begin_src emacs-lisp
(if (string-match "margil" (system-name)) "circleci" "gandi")
#+end_src

#+begin_src conf :tangle ~/.notmuch-config :noweb yes
[database]
path=/Users/stig/.mail

[user]
name=Stig Brautaset
primary_email=stig@brautaset.org
other_email=stig@circleci.com

[new]
tags=new;inbox
ignore=.mbsyncstate;.mbsyncstate.journal;.mbsyncstate.lock;.mbsyncstate.new;.uidvalidity;.isyncuidmap.db;.DS_Store

[search]
exclude_tags=deleted;spam;muted;<<ignore-tag()>>

[maildir]
synchronize_flags=true
#+end_src

* Script to run immediately before checking for new mail

Move messages based on tags, to avoid other email clients seing just a giant INBOX.

#+name: notmuch-search
#+begin_src sh :tangle no :padline no
notmuch search --exclude=false --output=files --format=text0
#+end_src

#+name: xargs-mv
#+begin_src sh :tangle no :padline no
xargs -0I % mv -fv %
#+end_src

#+name: mailbox
#+begin_src emacs-lisp
(if (string-match "margil" (system-name)) "gandi" "gmail")
#+end_src

#+BEGIN_SRC sh :tangle ~/.mail/.notmuch/hooks/pre-new :shebang #!/bin/zsh :tangle-mode (identity #o755) :mkdirp t :noweb yes
set -euo pipefail
IFS=$'\n\t'

echo "Pruning deleted drafts.."
<<notmuch-search>> -- tag:deleted and tag:draft | xargs -0 rm -fv

echo "Move deleted mail to Trash.."
<<notmuch-search>> -- tag:deleted and tag:gandi and not path:"gandi/Trash/**" \
    | <<xargs-mv>> ~/.mail/gandi/Trash/cur/ || true
<<notmuch-search>> -- tag:deleted and tag:gmail and not path "gmail/[Gmail]/Trash/**" \
    | <<xargs-mv>> ~/.mail/gmail/\[Gmail\]/Trash/cur || true

# echo "Expunge old deleted mail.."
# <<notmuch-search>> -- tag:deleted and path:/Trash/ and date:..4w | xargs -0 rm -fv

echo "Move spam in INBOX to correct folder on server.."
<<notmuch-search>> -- tag:spam and not tag:deleted and tag:gandi and not path:"gandi/Junk/**" \
    | <<xargs-mv>> ~/.mail/gandi/Junk/cur/ || true
<<notmuch-search>> -- tag:spam and not tag:deleted and tag:gmail and not path:"gmail/[Gmail]/Spam/**" \
    | <<xargs-mv>> ~/.mail/gmail/\[Gmail\]/Spam/cur/ || true

echo "Move incorrectly-tagged spam to INBOX.."
<<notmuch-search>> -- not tag:spam and tag:gandi and path:"gandi/Junk/**" \
    | <<xargs-mv>> ~/.mail/gandi/INBOX/cur/ || true
<<notmuch-search>> -- not tag:spam and tag:gmail and path:"gmail/[Gmail]/Spam/**" \
    | <<xargs-mv>> ~/.mail/gmail/INBOX/cur/ || true

echo "Remove 'new' tag for old messages.."
notmuch tag -new -- tag:new

echo "Synchronise local mailbox with upstream.."
mbsync <<mailbox()>>
#+END_SRC

* Script to run immediately after checking for new mail

Assign tags based on server filtering.

Propagate muted tag to new messages to muted threads. We must include
=tag:muted= in this search, and cannot include =tag:new=, otherwise
the search won't find anything.

Moreover I tag sent mail and remove it from my inbox. I decide whether
it's sent mail based on which mailbox it's in on the server.

Spam, archived, and deleted messages gets tagged as such, based on
their mailboxes on the server.

I don't normally want to see mailing list posts in my inbox, so remove
that tag. (And add specific tags based on their lists.)

Messages to particular aliases at my domain also gets tagged
appropriately.

Order confirmation messages from Amazon gets tagged so I can
batch-process them once a week.

Finally I tag some persistent spammers that are pretty good at getting
through my provider's spam filter, so they don't bother me.

#+BEGIN_SRC sh :tangle ~/.mail/.notmuch/hooks/post-new :shebang #!/bin/zsh :tangle-mode (identity #o755) :mkdirp t
notmuch tag --batch <<EOF
+muted -- tag:muted and thread:{tag:muted}

-inbox -unread +sent -- tag:new and path:/Sent/

-inbox +spam         -- tag:new and path:/Junk/
-inbox +archived     -- tag:new and path:/Archive/
-inbox +deleted      -- tag:new and path:/Trash/

+gandi    -- tag:new and path:"gandi/**"
+circleci -- tag:new and path:"gmail/**"

+lists +org-mode -inbox -- tag:new and to:emacs-orgmode@gnu.org
+lists +clojure -inbox  -- tag:new and to:clojure@googlegroups.com

# V. low volume lists gets to stay in inbox
+lists +tuls -- tag:new and to:tuls@debussy.pauken.co.uk

+fam         -- tag:new and to:fam@brautaset.org
+solve       -- tag:new and to:solve@brautaset.org

# Tag various common senders
+lobsters    -- tag:new and from:nobody@lobste.rs
+github      -- tag:new and from:notifications@github.com
+pagerduty   -- tag:new and from:no-reply@pagerduty.com
+linkedin    -- tag:new and from:messaging-digest-noreply@linkedin.com
+patreon     -- tag:new and from:bingo@patreon.com
+guitarhacks -- tag:new and from:support@guitarhacks.com

# Help me periodically confirm receipt of orders
+to_confirm -inbox -- tag:new and from:auto-confirm@amazon.co.uk

+spam -inbox -- tag:new and from:alexandre@les-caves.fr
+spam -inbox -- tag:new and from:alexandre@agence-gwa.com
+spam -inbox -- tag:new and from:replies@oracle-mail.com

EOF
#+END_SRC
